services:
    PcComponentes\DocumentationBundle\Service\Generator\OpenApiGenerator:
        class: PcComponentes\DocumentationBundle\Service\Generator\OpenApiGenerator
        arguments:
            - '@router'
            - '%kernel.project_dir%'

    PcComponentes\DocumentationBundle\Service\Generator\AsyncApiGenerator:
        class: PcComponentes\DocumentationBundle\Service\Generator\AsyncApiGenerator
        arguments:
            - '@router'
            - '%kernel.project_dir%'

    PcComponentes\DocumentationBundle\Service\Generator\ConvertersGenerator:
        class: PcComponentes\DocumentationBundle\Service\Generator\ConvertersGenerator
        arguments:
            - '@router'
            - '@PcComponentes\DocumentationBundle\Service\ConverterListing'

    PcComponentes\DocumentationBundle\Service\ConverterListing:
        class: PcComponentes\DocumentationBundle\Service\ConverterListing

    PcComponentes\DocumentationBundle\Service\LinkListing:
        class: PcComponentes\DocumentationBundle\Service\LinkListing

    PcComponentes\DocumentationBundle\Controller\OpenApiController:
        class: PcComponentes\DocumentationBundle\Controller\OpenApiController
        arguments:
            - '@PcComponentes\DocumentationBundle\Service\Generator\OpenApiGenerator'
        tags: ['controller.service_arguments']

    PcComponentes\DocumentationBundle\Controller\AsyncApiController:
        class: PcComponentes\DocumentationBundle\Controller\AsyncApiController
        arguments:
            - '@PcComponentes\DocumentationBundle\Service\Generator\AsyncApiGenerator'
        tags: ['controller.service_arguments']

    PcComponentes\DocumentationBundle\Controller\ConvertersController:
        class: PcComponentes\DocumentationBundle\Controller\ConvertersController
        arguments:
            - '@PcComponentes\DocumentationBundle\Service\Generator\ConvertersGenerator'
            - '@PcComponentes\DocumentationBundle\Service\ConverterListing'
        tags: ['controller.service_arguments']

    PcComponentes\DocumentationBundle\Controller\HomeController:
        class: PcComponentes\DocumentationBundle\Controller\HomeController
        arguments:
            - '@router'
            - '@PcComponentes\DocumentationBundle\Service\Generator\ConvertersGenerator'
            - '@PcComponentes\DocumentationBundle\Service\Generator\AsyncApiGenerator'
            - '@PcComponentes\DocumentationBundle\Service\Generator\OpenApiGenerator'
            - '@PcComponentes\DocumentationBundle\Service\LinkListing'
        tags: ['controller.service_arguments']