name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  phpunit-php7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: 'Run checkout'
      - run: make cache-folders build composer-install-7
        name: 'Build environment'
      - run: make tests-7
        name: 'Run unit tests'
  phpunit-php8:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v1
          name: 'Run checkout'
      -   run: make cache-folders build composer-install
          name: 'Build environment'
      -   run: make tests
          name: 'Run unit tests'